# Generated by Django 4.2 on 2024-07-13 04:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0003_remove_article_auther_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2024, 7, 13), verbose_name='تاریخ ثبت'),
            preserve_default=False,
        ),
    ]
