# Generated by Django 4.2 on 2024-07-19 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_module', '0005_articlecomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecomment',
            options={'verbose_name': 'نظر مقاله', 'verbose_name_plural': 'نظرات مقاله'},
        ),
    ]
